apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: guestbook
spec:
  ports:
  - port: 80
    nodePort: 32500
    targetPort: 80
    protocol: TCP
  selector:
    app: guestbook-ui
  type: NodePort
